import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/header'
import Hometop from '@/components/Hometop'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>GPTLetters</title>
        <meta name="description" content="Create unique and customized letters for any situation with GPTLetters. Our AI-powered platform generates high-quality letters in seconds. Choose from a variety of letter types, including love letters, business letters, cover letters, and more." />
        <meta name="description" content="How to write a cover letter" />
        <meta name="description" content="How to write an NDA" />
        <meta name="description" content="Love letters
            Business letters
            Cover letters
            Thank-you letters
            Recommendation letters
            Apology letters
            Resignation letters." />
        <meta name="description" content="Here are examples of how to write cover letters, GPTLetters is the way to craft your personalized letters with artificial intelligence" />
        <meta name="description" content="Say goodbye to writer's block! Our AI-powered platform creates unique and engaging letters for any occasion." />
        <meta name="description" content="Unlock the power of AI to create compelling letters that captivate your audience and drive results." />
        <meta name="description" content="Our platform uses advanced natural language processing to create letters that sound like they were written by a human." />
        <meta name="description" content="Save time and increase your productivity with our fast and efficient AI letter writing service." />
        <meta name="description" content="Whether you need business letters, personal letters, or any other type of correspondence, our platform has you covered." />
        <meta name="description" content="Impress your clients, colleagues, and loved ones with beautifully written letters generated by our AI platform." />
        <meta name="description" content="Say goodbye to boring, generic letters! Our AI-powered platform creates personalized, customized letters that resonate with your audience." />
        <meta name="description" content="Our easy-to-use platform allows you to quickly and easily generate high-quality letters without any prior writing experience." />
        <meta name="description" content="Get ahead of the curve and take advantage of the latest technology to create letters that stand out from the crowd. Try our AI-powered letter writing platform today!" />
        <meta name="description" content="Elevate your writing game with our AI-powered letter generator. Say goodbye to mediocrity and hello to excellence." />
        <meta name="description" content="Impress your readers with compelling letters written by our advanced AI algorithms. Experience the power of technology in every word." />
        <meta name="description" content="Our AI-powered platform creates letters that are not only engaging but also optimized for search engines, ensuring maximum visibility for your content." />
        <meta name="description" content="Generate letters in multiple languages with our advanced AI platform. Expand your reach and communicate with your audience no matter where they are." />
        <meta name="description" content="Our AI letter generator is perfect for businesses, writers, and anyone looking to create high-quality, professional letters with ease." />
        <meta name="description" content="Save money and resources with our AI-powered letter writing platform. Generate high-quality letters at a fraction of the cost of hiring a professional writer." />
        <meta name="description" content="Our platform uses machine learning to improve over time, ensuring that your letters are always cutting-edge and up-to-date with the latest trends." />
        <meta name="description" content="Let our AI platform create letters that are not just informative but also persuasive, driving your readers to take action." />
        <meta name="description" content="Our platform makes letter writing accessible to everyone, regardless of their writing ability or experience. Try our AI letter writing platform today and see the difference for yourself." />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hometop/>
    </>
    
  )
}
